version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoServer
    ports:
      - "8085:8000"
    environment:
      - DEBUG=True
