version: '3.8'

services:
  jenkins:
    image: jenkins-with-python
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  django:
    build: .
    container_name: django
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  jenkins_home:
