apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: fatih
  labels:
    helm.sh/chart: flask-apm-agent-demo-0.1.0
    app.kubernetes.io/name: apm-agent-demo
    app.kubernetes.io/instance: flask
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJrOHMtbWFzdGVyLWNvZGVjYW1wMjQub2Jzcy5pbzozMDAwMyI6IHsKICAgICAgInVzZXJuYW1lIjogImZhdGloLnlpbGRpcmltIiwKICAgICAgInBhc3N3b3JkIjogIjM3NE9IYlBMelF1dyIsCiAgICAgICJlbWFpbCI6ICJmYXRpaHlsZHJtMzY5M0BnbWFpbC5jb20iLAogICAgICAiYXV0aCI6ICJabUYwYVdndWVXbHNaR2x5YVcwNk16YzBUMGhpVUV4NlVYVjMiCiAgICB9CiAgfQp9Cg==
