apiVersion: v1
kind: Service
metadata:
  name: flask-apm-agent-demo
  namespace: fatih
  labels:
    helm.sh/chart: flask-apm-agent-demo-0.1.0
    app.kubernetes.io/name: apm-agent-demo
    app.kubernetes.io/instance: flask
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8085  
      targetPort: 8085
      protocol: TCP
      name: http
      nodePort: 31017
  selector:
    app.kubernetes.io/name: apm-agent-demo
    app.kubernetes.io/instance: flask